---
created: '2025-10-29T21:19:29.329810+00:00'
creator: sentry
source: tests/sentry/grouping/test_grouping_info.py
---
{
  "app_exception_message": {
    "component": {
      "contributes": true,
      "hint": null,
      "id": "app",
      "name": "in-app",
      "values": [
        {
          "contributes": true,
          "hint": null,
          "id": "exception",
          "name": "exception",
          "values": [
            {
              "contributes": true,
              "hint": null,
              "id": "type",
              "name": null,
              "values": [
                "Error"
              ]
            },
            {
              "contributes": true,
              "hint": null,
              "id": "value",
              "name": null,
              "values": [
                "There was an error during concurrent rendering but React was able to recover by instead synchronously rendering the entire root."
              ]
            },
            {
              "contributes": false,
              "hint": null,
              "id": "stacktrace",
              "name": "stacktrace",
              "values": []
            }
          ]
        }
      ]
    },
    "config": {
      "base": "newstyle:2023-01-11",
      "delegates": [
        "frame:v1",
        "single-exception:v1",
        "stacktrace:v1"
      ],
      "id": "newstyle:2025-11-21",
      "strategies": [
        "chained-exception:v1",
        "csp:v1",
        "expect-ct:v1",
        "expect-staple:v1",
        "hpkp:v1",
        "message:v1",
        "stacktrace:v1",
        "template:v1",
        "threads:v1"
      ]
    },
    "contributes": true,
    "description": "exception message",
    "hash": "70dd09f56349dcce62a74137b00bb571",
    "hint": null,
    "key": "app_exception_message",
    "type": "component"
  }
}
